name: Publish to CWS.

on:
  push:
    tags:
      - '*' 
      - '**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 21

      - name: Install dependencies
        run: npm install

      - name: Build zip file
        run: npm run build

      - name: Upload to Chrome Web Store
        uses: mobilefirstllc/cws-publish@latest
        with:
          action: 'upload' 
          client_id: ${{ secrets.G_CLIENT_ID }}
          client_secret: ${{ secrets.G_CLIENT_SECRET }}
          refresh_token: ${{ secrets.G_REFRESH_TOKEN }}
          extension_id: ${{ secrets.EXTENSION_ID }}
          zip_file: 'extension.zip'
