name: Tests and publishing

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main

jobs:
  test_linux:
    name: Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 21
      - name: Install dependencies
        run: npm ci
      - name: Run test
        run: npm test
  tag:
    name: "Publishing Tag"
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    needs: 
      - test_linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: 21
          registry-url: 'https://registry.npmjs.org'
      - run: npm install
      - name: Read version from package.json
        uses: culshaw/read-package-node-version-actions@v1
        id: package-node-version
      - name: Changelog
        uses: scottbrenner/generate-changelog-action@master
        id: Changelog
      - name: Github Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.package-node-version.outputs.version }}
          release_name: v${{ steps.package-node-version.outputs.version }}
          body: |
            ${{ steps.Changelog.outputs.changelog }}
          draft: false
          prerelease: false
